// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SizzEvent.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "SizzEvent.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
// @@protoc_insertion_point(includes)

namespace SizzEvent {

void protobuf_ShutdownFile_SizzEvent_2eproto() {
  delete SizzEvent::default_instance_;
  delete SizzEvent_EventData::default_instance_;
}

#ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
void protobuf_AddDesc_SizzEvent_2eproto_impl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

#else
void protobuf_AddDesc_SizzEvent_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

#endif
  SizzEvent::default_instance_ = new SizzEvent();
  SizzEvent_EventData::default_instance_ = new SizzEvent_EventData();
  SizzEvent::default_instance_->InitAsDefaultInstance();
  SizzEvent_EventData::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_SizzEvent_2eproto);
}

#ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AddDesc_SizzEvent_2eproto_once_);
void protobuf_AddDesc_SizzEvent_2eproto() {
  ::google::protobuf::::google::protobuf::GoogleOnceInit(&protobuf_AddDesc_SizzEvent_2eproto_once_,
                 &protobuf_AddDesc_SizzEvent_2eproto_impl);
}
#else
// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_SizzEvent_2eproto {
  StaticDescriptorInitializer_SizzEvent_2eproto() {
    protobuf_AddDesc_SizzEvent_2eproto();
  }
} static_descriptor_initializer_SizzEvent_2eproto_;
#endif

// ===================================================================

bool SizzEvent_EventData_DATA_TYPES_IsValid(int value) {
  switch(value) {
    case 1:
    case 2:
    case 3:
      return true;
    default:
      return false;
  }
}

#ifndef _MSC_VER
const SizzEvent_EventData_DATA_TYPES SizzEvent_EventData::TYPE_STRING;
const SizzEvent_EventData_DATA_TYPES SizzEvent_EventData::TYPE_INT;
const SizzEvent_EventData_DATA_TYPES SizzEvent_EventData::TYPE_FLOAT;
const SizzEvent_EventData_DATA_TYPES SizzEvent_EventData::DATA_TYPES_MIN;
const SizzEvent_EventData_DATA_TYPES SizzEvent_EventData::DATA_TYPES_MAX;
const int SizzEvent_EventData::DATA_TYPES_ARRAYSIZE;
#endif  // _MSC_VER
#ifndef _MSC_VER
const int SizzEvent_EventData::kDataKeyFieldNumber;
const int SizzEvent_EventData::kDataValueFieldNumber;
const int SizzEvent_EventData::kDataTypeFieldNumber;
const int SizzEvent_EventData::kDataLengthFieldNumber;
#endif  // !_MSC_VER

SizzEvent_EventData::SizzEvent_EventData()
  : ::google::protobuf::MessageLite() {
  SharedCtor();
}

void SizzEvent_EventData::InitAsDefaultInstance() {
}

SizzEvent_EventData::SizzEvent_EventData(const SizzEvent_EventData& from)
  : ::google::protobuf::MessageLite() {
  SharedCtor();
  MergeFrom(from);
}

void SizzEvent_EventData::SharedCtor() {
  _cached_size_ = 0;
  data_key_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  data_value_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  data_type_ = 1;
  data_length_ = 0u;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

SizzEvent_EventData::~SizzEvent_EventData() {
  SharedDtor();
}

void SizzEvent_EventData::SharedDtor() {
  if (data_key_ != &::google::protobuf::internal::kEmptyString) {
    delete data_key_;
  }
  if (data_value_ != &::google::protobuf::internal::kEmptyString) {
    delete data_value_;
  }
  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  if (this != &default_instance()) {
  #else
  if (this != default_instance_) {
  #endif
  }
}

void SizzEvent_EventData::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const SizzEvent_EventData& SizzEvent_EventData::default_instance() {
#ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  protobuf_AddDesc_SizzEvent_2eproto();
#else
  if (default_instance_ == NULL) protobuf_AddDesc_SizzEvent_2eproto();
#endif
  return *default_instance_;
}

SizzEvent_EventData* SizzEvent_EventData::default_instance_ = NULL;

SizzEvent_EventData* SizzEvent_EventData::New() const {
  return new SizzEvent_EventData;
}

void SizzEvent_EventData::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (has_data_key()) {
      if (data_key_ != &::google::protobuf::internal::kEmptyString) {
        data_key_->clear();
      }
    }
    if (has_data_value()) {
      if (data_value_ != &::google::protobuf::internal::kEmptyString) {
        data_value_->clear();
      }
    }
    data_type_ = 1;
    data_length_ = 0u;
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

bool SizzEvent_EventData::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required string data_key = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_data_key()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(18)) goto parse_data_value;
        break;
      }

      // required bytes data_value = 2;
      case 2: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_data_value:
          DO_(::google::protobuf::internal::WireFormatLite::ReadBytes(
                input, this->mutable_data_value()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(24)) goto parse_data_type;
        break;
      }

      // optional .SizzEvent.SizzEvent.EventData.DATA_TYPES data_type = 3;
      case 3: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_data_type:
          int value;
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   int, ::google::protobuf::internal::WireFormatLite::TYPE_ENUM>(
                 input, &value)));
          if (::SizzEvent::SizzEvent_EventData_DATA_TYPES_IsValid(value)) {
            set_data_type(static_cast< ::SizzEvent::SizzEvent_EventData_DATA_TYPES >(value));
          }
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(32)) goto parse_data_length;
        break;
      }

      // optional uint32 data_length = 4;
      case 4: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_data_length:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &data_length_)));
          set_has_data_length();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }

      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void SizzEvent_EventData::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // required string data_key = 1;
  if (has_data_key()) {
    ::google::protobuf::internal::WireFormatLite::WriteString(
      1, this->data_key(), output);
  }

  // required bytes data_value = 2;
  if (has_data_value()) {
    ::google::protobuf::internal::WireFormatLite::WriteBytes(
      2, this->data_value(), output);
  }

  // optional .SizzEvent.SizzEvent.EventData.DATA_TYPES data_type = 3;
  if (has_data_type()) {
    ::google::protobuf::internal::WireFormatLite::WriteEnum(
      3, this->data_type(), output);
  }

  // optional uint32 data_length = 4;
  if (has_data_length()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(4, this->data_length(), output);
  }

}

int SizzEvent_EventData::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required string data_key = 1;
    if (has_data_key()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->data_key());
    }

    // required bytes data_value = 2;
    if (has_data_value()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::BytesSize(
          this->data_value());
    }

    // optional .SizzEvent.SizzEvent.EventData.DATA_TYPES data_type = 3;
    if (has_data_type()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::EnumSize(this->data_type());
    }

    // optional uint32 data_length = 4;
    if (has_data_length()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::UInt32Size(
          this->data_length());
    }

  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void SizzEvent_EventData::CheckTypeAndMergeFrom(
    const ::google::protobuf::MessageLite& from) {
  MergeFrom(*::google::protobuf::down_cast<const SizzEvent_EventData*>(&from));
}

void SizzEvent_EventData::MergeFrom(const SizzEvent_EventData& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_data_key()) {
      set_data_key(from.data_key());
    }
    if (from.has_data_value()) {
      set_data_value(from.data_value());
    }
    if (from.has_data_type()) {
      set_data_type(from.data_type());
    }
    if (from.has_data_length()) {
      set_data_length(from.data_length());
    }
  }
}

void SizzEvent_EventData::CopyFrom(const SizzEvent_EventData& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool SizzEvent_EventData::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000003) != 0x00000003) return false;

  return true;
}

void SizzEvent_EventData::Swap(SizzEvent_EventData* other) {
  if (other != this) {
    std::swap(data_key_, other->data_key_);
    std::swap(data_value_, other->data_value_);
    std::swap(data_type_, other->data_type_);
    std::swap(data_length_, other->data_length_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::std::string SizzEvent_EventData::GetTypeName() const {
  return "SizzEvent.SizzEvent.EventData";
}


// -------------------------------------------------------------------

#ifndef _MSC_VER
const int SizzEvent::kMessageVersionFieldNumber;
const int SizzEvent::kTimestampFieldNumber;
const int SizzEvent::kNameFieldNumber;
const int SizzEvent::kEventDataFieldNumber;
#endif  // !_MSC_VER

SizzEvent::SizzEvent()
  : ::google::protobuf::MessageLite() {
  SharedCtor();
}

void SizzEvent::InitAsDefaultInstance() {
}

SizzEvent::SizzEvent(const SizzEvent& from)
  : ::google::protobuf::MessageLite() {
  SharedCtor();
  MergeFrom(from);
}

void SizzEvent::SharedCtor() {
  _cached_size_ = 0;
  message_version_ = 0u;
  timestamp_ = 0u;
  name_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

SizzEvent::~SizzEvent() {
  SharedDtor();
}

void SizzEvent::SharedDtor() {
  if (name_ != &::google::protobuf::internal::kEmptyString) {
    delete name_;
  }
  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  if (this != &default_instance()) {
  #else
  if (this != default_instance_) {
  #endif
  }
}

void SizzEvent::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const SizzEvent& SizzEvent::default_instance() {
#ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  protobuf_AddDesc_SizzEvent_2eproto();
#else
  if (default_instance_ == NULL) protobuf_AddDesc_SizzEvent_2eproto();
#endif
  return *default_instance_;
}

SizzEvent* SizzEvent::default_instance_ = NULL;

SizzEvent* SizzEvent::New() const {
  return new SizzEvent;
}

void SizzEvent::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    message_version_ = 0u;
    timestamp_ = 0u;
    if (has_name()) {
      if (name_ != &::google::protobuf::internal::kEmptyString) {
        name_->clear();
      }
    }
  }
  event_data_.Clear();
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

bool SizzEvent::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required uint32 message_version = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &message_version_)));
          set_has_message_version();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(16)) goto parse_timestamp;
        break;
      }

      // required uint32 timestamp = 2;
      case 2: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_timestamp:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &timestamp_)));
          set_has_timestamp();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(26)) goto parse_name;
        break;
      }

      // required string name = 3;
      case 3: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_name:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_name()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(34)) goto parse_event_data;
        break;
      }

      // repeated .SizzEvent.SizzEvent.EventData event_data = 4;
      case 4: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_event_data:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
                input, add_event_data()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(34)) goto parse_event_data;
        if (input->ExpectAtEnd()) return true;
        break;
      }

      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void SizzEvent::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // required uint32 message_version = 1;
  if (has_message_version()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(1, this->message_version(), output);
  }

  // required uint32 timestamp = 2;
  if (has_timestamp()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(2, this->timestamp(), output);
  }

  // required string name = 3;
  if (has_name()) {
    ::google::protobuf::internal::WireFormatLite::WriteString(
      3, this->name(), output);
  }

  // repeated .SizzEvent.SizzEvent.EventData event_data = 4;
  for (int i = 0; i < this->event_data_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessage(
      4, this->event_data(i), output);
  }

}

int SizzEvent::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required uint32 message_version = 1;
    if (has_message_version()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::UInt32Size(
          this->message_version());
    }

    // required uint32 timestamp = 2;
    if (has_timestamp()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::UInt32Size(
          this->timestamp());
    }

    // required string name = 3;
    if (has_name()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->name());
    }

  }
  // repeated .SizzEvent.SizzEvent.EventData event_data = 4;
  total_size += 1 * this->event_data_size();
  for (int i = 0; i < this->event_data_size(); i++) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        this->event_data(i));
  }

  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void SizzEvent::CheckTypeAndMergeFrom(
    const ::google::protobuf::MessageLite& from) {
  MergeFrom(*::google::protobuf::down_cast<const SizzEvent*>(&from));
}

void SizzEvent::MergeFrom(const SizzEvent& from) {
  GOOGLE_CHECK_NE(&from, this);
  event_data_.MergeFrom(from.event_data_);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_message_version()) {
      set_message_version(from.message_version());
    }
    if (from.has_timestamp()) {
      set_timestamp(from.timestamp());
    }
    if (from.has_name()) {
      set_name(from.name());
    }
  }
}

void SizzEvent::CopyFrom(const SizzEvent& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool SizzEvent::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000007) != 0x00000007) return false;

  for (int i = 0; i < event_data_size(); i++) {
    if (!this->event_data(i).IsInitialized()) return false;
  }
  return true;
}

void SizzEvent::Swap(SizzEvent* other) {
  if (other != this) {
    std::swap(message_version_, other->message_version_);
    std::swap(timestamp_, other->timestamp_);
    std::swap(name_, other->name_);
    event_data_.Swap(&other->event_data_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::std::string SizzEvent::GetTypeName() const {
  return "SizzEvent.SizzEvent";
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace SizzEvent

// @@protoc_insertion_point(global_scope)
